### ISSUE TITLE
Blog post comments: QUIC in .NET - Comparison and Interop with msquic

### ISSUE THREAD

**Issue by rzikm** [rzikm/rzikm.github.io#3]
https://rzikm.github.io/quic-in-net-comparison-with-msquic/

**Comment by nibanks** [comment]
Would you be able to clarify exactly what was tested in the `Performance Comparisons with MsQuic-based Implementation` section of your blog?

**Comment by rzikm** [comment]
Hi, the benchmark measured how long it took on the client to send a chunk of data of particular size + wait for graceful shutdown. For each iteration, the connection was established anew and the time of connection establishment was not included in the benchmark.

However, it was really a primitive test run over localhost. I just wanted to get at least some idea where my implementation stands. I have done a slightly better comparison for the text of my master thesis which gave different result (in favor of MsQuic). You can find a copy of the thesis at https://1drv.ms/b/s!ApmFa_iO60n7jJJE7aUtFmmerItxeg. The measurements plus my interpretation is in the last chapter. The measurements setup in the thesis text used a simple echo server+client and part of the evaluation was how my implementation scaled with increasing number of streams/connections. 

I would be glad to have a chat about this over Skype/Teams if you have more questions.

**Comment by nibanks** [comment]
I would be interested to discuss things further with you. Do you mind sending email to my Microsoft email address and we can set something up?
